import "./globals.css";
import React from "react";
import ReduxWrapper from "../core/redux/ReduxWrapper";
import { PrivateRoute } from "../core/components/PrivateRoute";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

// standard stylesheets cannot be imported on component-level
// to avoid always loading this, AuthBox need to be converted to use css-modules or another
// supported method
import "../core/components/AuthBox/styles.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <head>
        <title>Hufschuhapp Auswertung</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ReduxWrapper>
          <PrivateRoute>{children}</PrivateRoute>
        </ReduxWrapper>
      </body>
    </html>
  );
}
